// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxhcxszguceszkucmaqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54aGN4c3pndWNlc3prdWNtYXFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MDY0MjYsImV4cCI6MjA2Mjk4MjQyNn0.pQdPMLOY53-ZZKdHsfCP2Z-OGUAQGO2nWiofofFVWNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);